Choices = {
    "1":"This is a basic text-based game called The Mysterious Mansion, You find yourself standing in front of a grand mansion. The door creaks open invitingly. Do you enter? (Type yes or no)",
    "1f":"The mysterious mansion remains a tantalizing mystery, and you decide to turn back and leave. As you walk away, you can't help but wonder about the secrets that lie within.",
    "2":"As you step inside, the door slams shut behind you, and you hear it lock. You're trapped! The only way out is to solve the mansion's mysteries. You notice two hallways stretching out before you. One is brightly lit, and the other is shrouded in darkness. Which way do you go? (Type left or right)",
    "2f":"You cautiously proceed down the dark hallway. With each step, the darkness seems to engulf you. Suddenly, you stumble upon a hidden trapdoor, and it gives way beneath you. You fall into a pit, and your journey ends there.",
    "3":"You cautiously proceed down the brightly lit hallway. At the end, you find a room with a large table and two cups on it. Each cup contains a different colored liquid: red, blue, and green. There's a note that reads, (Choose wisely. Only one cup leads to the next clue.) Which cup do you drink from? (Type red or blue)",
    "3f":"You take a sip from the red cup. Immediately, you feel a burning sensation spreading through your body. The liquid was poisonous, and you collapse to the ground, unable to continue your exploration.",
    "4":"You take a sip from the blue cup. It tastes strange, but you feel a surge of energy. The room starts spinning, and suddenly, you're transported to a different part of the mansion. You find yourself in a dimly lit library. There are several bookshelves filled with dusty books. On one shelf, you notice a book with a peculiar title: The Forgotten Key. Do you pick up the book? (Type yes or no)",
    "4f":"You decide to leave the book on the shelf and continue exploring the library. However, without the key, you are unable to progress further in your quest. You wander through the mansion, but ultimately, you find no way out.",
    "5":"You grab the book titled The Forgotten Key and open it. Inside, you find a small key hidden within its pages. As you hold the key, a secret door in the library slides open, revealing a hidden staircase. Will you descend the staircase? (Type yes or no)",
    "5f":"You decide against going down the mysterious staircase and continue exploring the mansion. However, as you wander aimlessly, you stumble upon a dead-end and realize there's no way forward. Trapped and without a clue, your adventure comes to an end.",
    "6":"You descend the staircase, and it leads you to a damp underground chamber. There's a locked chest in the corner of the room. You try the key you found in the book, and it fits perfectly. You open the chest and discover a sparkling gem inside. As you reach for it, the room begins to rumble. The walls are closing in! Do you grab the gem and make a run for it? (Type yes or no)",
    "6f":"As the room's walls close in, you hesitate to grab the gem, fearing it might be a trap. Unfortunately, the hesitation costs you precious time, and you're unable to escape the room before it seals shut. Your journey in the mysterious mansion ends there.",
    "7":"You snatch the gem and dash towards the staircase just in time. The room seals shut behind you as you make your way back to the main hallway. With the gem in your possession, you discover it has the power to unlock the mansion's front door. You escape the mysterious mansion, victorious!",
    "8":"Congratulations! You have successfully completed The Mysterious Mansion!",
    "End":"How could you fail the captain like this?."
}